// AUTO-GENERATED by scripts/gen-pi-schemas.ts from pi/schemas/. DO NOT EDIT.
// Regenerate with `bun run gen:pi-schemas`; run-all verifies drift via `check:pi-schemas`.

export const AskUserQuestionParameters = {
  type: "object",
  properties: {
    questions: {
      type: "array",
      items: {
        type: "object",
        properties: {
          question: {
            type: "string",
            description: "The complete question to ask",
          },
          header: {
            type: "string",
            description: "Short label for the question",
          },
          multiSelect: {
            type: "boolean",
            description: "Whether the user may select multiple options",
          },
          options: {
            type: "array",
            items: {
              type: "object",
              properties: {
                label: {
                  type: "string",
                  description: "Display label for the option",
                },
                description: {
                  type: "string",
                  description: "Explanation shown alongside the option",
                },
                preview: {
                  type: "string",
                  description:
                    "Optional preview associated with selecting the option",
                },
              },
              required: ["label", "description"],
              additionalProperties: true,
            },
            minItems: 2,
            maxItems: 4,
            description:
              "Choices presented to the user; Other is added automatically",
          },
        },
        required: ["question", "header", "multiSelect", "options"],
        additionalProperties: true,
      },
      minItems: 1,
      maxItems: 4,
      description: "One to four questions to ask in a single call",
    },
  },
  required: ["questions"],
  additionalProperties: true,
} as const;
