/**
 * Ahead-of-time schema compiler for pi-harness tool parameters.
 *
 * Reads the tskm source-of-truth schemas under pi/schemas/, converts each to a
 * plain JSON Schema object via @tskm/compiler, and writes committed
 * `parameters.generated.ts` files (plain object literals, `as const`) into the
 * extension. The extension imports those relatively and never depends on tskm
 * at runtime — this keeps pi-harness self-contained (check-pi-imports).
 *
 * Modes:
 *   (default)  regenerate and write the committed files atomically.
 *   --check    regenerate in memory and byte-compare against the committed
 *              files; exit 1 on any drift WITHOUT writing. Wired into run-all
 *              (before the mutating `format --write`) so source edits that
 *              forget regeneration fail CI.
 *
 * Determinism + atomicity (so the drift check is reliable):
 *   - All schemas are converted first; warnings are aggregated and, if any
 *     appear, the run throws BEFORE writing anything (an unrepresentable
 *     construct — e.g. a dropped description — must never be silently emitted).
 *   - Rendering is deterministic (schemaToJsonSchema emits stable key order;
 *     prettier normalizes formatting using the repo config resolved from the
 *     target path).
 *   - Writes go to a temp sibling then rename, so a mid-run failure never
 *     leaves a half-written committed file.
 */
import { readFile, rename, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { schemaToJsonSchema } from "@tskm/compiler";
import { format, resolveConfig } from "prettier";
import { SubagentParameters } from "../pi/schemas/subagent";
import {
  TaskCompletedParameters,
  WorktreeCreateParameters,
  WorktreeRemoveParameters,
} from "../pi/schemas/bit-task";
import { WorkflowParameters } from "../pi/schemas/workflow";

const REPO_ROOT = resolve(import.meta.dir, "..");
const FEATURES_DIR = join(REPO_ROOT, "pi/extensions/pi-harness/features");

interface Target {
  /** feature directory under pi/extensions/pi-harness/features */
  feature: string;
  /** exported schema name -> tskm runtime schema object */
  schemas: Record<string, unknown>;
}

// Only the schemas actually passed to registerTool are exported. Nested
// schemas (TaskItemSchema, WorkflowStageParameters, ...) stay internal to the
// tskm source and are inlined into their parent's JSON Schema.
const TARGETS: Target[] = [
  { feature: "subagent", schemas: { SubagentParameters } },
  {
    feature: "bit-task",
    schemas: {
      WorktreeCreateParameters,
      WorktreeRemoveParameters,
      TaskCompletedParameters,
    },
  },
  { feature: "workflow", schemas: { WorkflowParameters } },
];

const HEADER = `// AUTO-GENERATED by scripts/gen-pi-schemas.ts from pi/schemas/. DO NOT EDIT.
// Regenerate with \`bun run gen:pi-schemas\`; run-all verifies drift via \`check:pi-schemas\`.
`;

const generatedPath = (feature: string): string =>
  join(FEATURES_DIR, feature, "parameters.generated.ts");

/** Convert every target's schemas; throw (before any write) if any warns. */
const renderAll = async (): Promise<Map<string, string>> => {
  const rendered = new Map<string, string>();
  const warnings: string[] = [];

  for (const target of TARGETS) {
    const blocks: string[] = [];
    for (const [name, schema] of Object.entries(target.schemas)) {
      const result = schemaToJsonSchema(schema);
      for (const warning of result.warnings) {
        warnings.push(`${target.feature}.${name}: ${warning}`);
      }
      blocks.push(
        `export const ${name} = ${JSON.stringify(result.schema)} as const;`,
      );
    }
    const path = generatedPath(target.feature);
    const source = `${HEADER}\n${blocks.join("\n\n")}\n`;
    const config = await resolveConfig(path);
    rendered.set(path, await format(source, { ...config, filepath: path }));
  }

  if (warnings.length > 0) {
    throw new Error(
      `gen-pi-schemas: ${warnings.length} unrepresentable construct(s); refusing to write:\n- ${warnings.join("\n- ")}`,
    );
  }
  return rendered;
};

const main = async (): Promise<void> => {
  const checkOnly = process.argv.includes("--check");
  const rendered = await renderAll();

  if (checkOnly) {
    const drifted: string[] = [];
    for (const [path, content] of rendered) {
      let current: string | undefined;
      try {
        current = await readFile(path, "utf8");
      } catch {
        current = undefined;
      }
      if (current !== content) drifted.push(path);
    }
    if (drifted.length > 0) {
      console.error(
        `check-pi-schemas: ${drifted.length} generated file(s) out of date; run \`bun run gen:pi-schemas\`:`,
      );
      for (const path of drifted) console.error(`  - ${path}`);
      process.exit(1);
    }
    console.log("check-pi-schemas: OK");
    return;
  }

  for (const [path, content] of rendered) {
    const temp = `${path}.tmp`;
    await writeFile(temp, content, "utf8");
    await rename(temp, path);
  }
  console.log(`gen-pi-schemas: wrote ${rendered.size} file(s)`);
};

await main();
