// AUTO-GENERATED by scripts/gen-pi-schemas.ts from pi/schemas/. DO NOT EDIT.
// Regenerate with `bun run gen:pi-schemas`; run-all verifies drift via `check:pi-schemas`.

export const MemoryRecallParameters = {
  type: "object",
  properties: {
    action: {
      anyOf: [{ const: "list" }, { const: "show" }, { const: "sessions" }],
      description: "Aggregated read operation",
    },
    path: {
      type: "string",
      maxLength: 256,
      description: "Logical project-memory path required by show",
    },
  },
  required: ["action"],
  additionalProperties: true,
} as const;

export const MemoryUpdateParameters = {
  type: "object",
  properties: {
    action: {
      anyOf: [{ const: "put" }, { const: "remove" }],
      description: "Session-scoped memory mutation",
    },
    path: {
      type: "string",
      maxLength: 256,
      description: "Logical project-memory path",
    },
    description: {
      type: "string",
      maxLength: 512,
      description: "One-line index description required by put",
    },
    content: {
      type: "string",
      maxLength: 32768,
      description: "Markdown data required by put",
    },
  },
  required: ["action", "path"],
  additionalProperties: true,
} as const;
