// AUTO-GENERATED by scripts/gen-pi-schemas.ts from pi/schemas/. DO NOT EDIT.
// Regenerate with `bun run gen:pi-schemas`; run-all verifies drift via `check:pi-schemas`.

export const SubagentStatusParameters = {
  type: "object",
  properties: {
    invocationId: {
      type: "string",
      description: "Invocation ID returned by subagent or workflow",
    },
  },
  required: ["invocationId"],
  additionalProperties: true,
} as const;
