// AUTO-GENERATED by scripts/gen-pi-schemas.ts from pi/schemas/. DO NOT EDIT.
// Regenerate with `bun run gen:pi-schemas`; run-all verifies drift via `check:pi-schemas`.

export const WorkflowParameters = {
  type: "object",
  properties: {
    stages: {
      type: "array",
      items: {
        type: "object",
        properties: {
          name: { type: "string", description: "Stage label for the report" },
          mode: { anyOf: [{ const: "fanout" }, { const: "single" }] },
          codexSkip: {
            type: "boolean",
            description:
              "Explicit user opt-out from the codex mandate for this fan-out stage",
          },
          tasks: {
            type: "array",
            items: {
              type: "object",
              properties: {
                agentType: {
                  type: "string",
                  description:
                    "Agent to run; fan-out tasks default to codex-reviewer (codex mandate)",
                },
                task: {
                  type: "string",
                  description: "Task delegated to the agent",
                },
                cwd: {
                  type: "string",
                  description: "Working directory (not allowed with isolation)",
                },
                isolation: {
                  const: "worktree",
                  description:
                    "Provision an isolated linked worktree as the task cwd (required for codex-poc)",
                },
                readOnly: {
                  type: "boolean",
                  description:
                    "Restrict the child to the read tool; the task must carry a validated transport-safe snapshot path",
                },
                writeScope: {
                  type: "array",
                  items: { type: "string" },
                  description:
                    "Paths this task may write; required and pairwise disjoint for parallel codex-runner tasks",
                },
              },
              required: ["task"],
              additionalProperties: true,
            },
            maxItems: 8,
            description: "Tasks in this stage",
          },
        },
        required: ["mode", "tasks"],
        additionalProperties: true,
      },
      maxItems: 8,
      description: "Stages executed sequentially",
    },
  },
  required: ["stages"],
  additionalProperties: true,
} as const;
