model = "gpt-5.5"
model_reasoning_effort = "xhigh"
personality = "pragmatic"
service_tier = "fast"

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[tui.model_availability_nux]
"gpt-5.5" = 4

[desktop]
usePointerCursors = true

[desktop.appearanceLightChromeTheme]
accent = "#339cff"
contrast = 50
ink = "#1a1c1f"
opaqueWindows = false
surface = "#ffffff"

[desktop.appearanceLightChromeTheme.fonts]

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#00a240"
diffRemoved = "#ba2623"
skill = "#924ff7"

[desktop.appearanceDarkChromeTheme]
accent = "#339cff"
contrast = 60
ink = "#ffffff"
opaqueWindows = false
surface = "#181818"

[desktop.appearanceDarkChromeTheme.fonts]

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#40c977"
diffRemoved = "#fa423e"
skill = "#ad7bf9"

[desktop.open-in-target-preferences]
global = "ghostty"

[features]
js_repl = false

