[tools]
helix = "latest"
node = "24.6.0"
starship = "latest"
ni = "23.2.0"
pnpm = "latest"
rust = "latest"
uv = "latest"
bun = "latest"
jq = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
ffmpeg = "latest"
"github:ushironoko/octorus" = "0.5.8"
"github:ushironoko/abbrs" = "latest"
"github:ushironoko/gitfilm" = "latest"
"github:bit-vcs/bit" = "0.35.2"
"github:ast-grep/ast-grep" = "latest"
"github:d-kuro/gwq" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[env]
