[tools]
helix = "25.07.1"
node = "24.6.0"
starship = "1.25.1"
ni = "30.1.0"
pnpm = "11.0.9"
rust = "1.95.0"
uv = "0.11.13"
bun = "1.3.13"
jq = "1.8.1"
fzf = "0.72.0"
gh = "2.92.0"
ghq = "1.10.1"
ffmpeg = "8.0.1"
"github:ushironoko/octorus" = "0.6.4"
"github:ushironoko/abbrs" = "0.2.10"
"github:ushironoko/gitfilm" = "0.3.0"
"github:bit-vcs/bit" = "0.35.2"
"github:ast-grep/ast-grep" = "0.42.2"
"github:d-kuro/gwq" = "0.1.1"
gcloud = "567.0.0"
"github:koalaman/shellcheck" = "v0.10.0"
tmux = "3.6a"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[env]
