// AUTO-GENERATED by scripts/gen-pi-schemas.ts from pi/schemas/. DO NOT EDIT.
// Regenerate with `bun run gen:pi-schemas`; run-all verifies drift via `check:pi-schemas`.

export const WorktreeCreateParameters = {
  type: "object",
  properties: {
    name: { type: "string", description: "Branch name for the new worktree" },
  },
  required: ["name"],
  additionalProperties: true,
} as const;

export const WorktreeRemoveParameters = {
  type: "object",
  properties: {
    path: {
      type: "string",
      description: "Absolute path of the linked worktree",
    },
    confirmed: {
      type: "boolean",
      description: "True only after the user explicitly approved removal",
    },
  },
  required: ["path", "confirmed"],
  additionalProperties: true,
} as const;

export const TaskCompletedParameters = {
  type: "object",
  properties: {
    task_id: { type: "string", description: "Stable task compatibility id" },
    task_subject: {
      type: "string",
      description: "Human-readable completed task subject",
    },
  },
  required: ["task_id"],
  additionalProperties: true,
} as const;
