// AUTO-GENERATED by scripts/gen-pi-schemas.ts from pi/schemas/. DO NOT EDIT.
// Regenerate with `bun run gen:pi-schemas`; run-all verifies drift via `check:pi-schemas`.

export const SubagentParameters = {
  type: "object",
  properties: {
    agent: { type: "string", description: "Name of the agent for single mode" },
    task: { type: "string", description: "Task to delegate for single mode" },
    tasks: {
      type: "array",
      items: {
        type: "object",
        properties: {
          agent: { type: "string", description: "Name of the agent to invoke" },
          task: {
            type: "string",
            description: "Task to delegate to the agent",
          },
          cwd: {
            type: "string",
            description: "Working directory for the agent process",
          },
        },
        required: ["agent", "task"],
        additionalProperties: true,
      },
      maxItems: 8,
      description: "Tasks to run in parallel",
    },
    chain: {
      type: "array",
      items: {
        type: "object",
        properties: {
          agent: { type: "string", description: "Name of the agent to invoke" },
          task: {
            type: "string",
            description: "Task with an optional {previous} placeholder",
          },
          cwd: {
            type: "string",
            description: "Working directory for the agent process",
          },
        },
        required: ["agent", "task"],
        additionalProperties: true,
      },
      maxItems: 8,
      description: "Tasks to run sequentially",
    },
    cwd: { type: "string", description: "Working directory for single mode" },
  },
  required: [],
  additionalProperties: true,
} as const;
